### ISSUE TITLE
DynamicAttentionWrapper'

### ISSUE THREAD

**Issue by kiranvarghesev** [Currie32/Spell-Checker#3]
dec_cell = tf.contrib.seq2seq.DynamicAttentionWrapper(dec_cell,

AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'

**Comment by FurKan7** [comment]
you need to use tensorflow 1.1 version

**Comment by pakgya** [comment]
use AttentionWrapper and covert initial state to:
initial_state=dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)

**Comment by yashugupta786** [comment]
Hi i have changed the DynamicAttentionWrapper to 
dec_cell = tf.contrib.seq2seq.AttentionWrapper(dec_cell,
                                                              attn_mech,
                                                              rnn_size)
and intial state to
initial_state = dec_cell.zero_state(batch_size=batch_size, dtype=tf.float32).clone(cell_state=enc_state)

but i am getting errors like
initial_state = dec_cell.zero_state(batch_size=batch_size, dtype=tf.float32).clone(cell_state=enc_state)

please help

**Comment by pranav774** [comment]
I am using tensorflow version 1.8 , I have changed the  DynamicAttentionWrapper to AttentionWrapper.
but i am getting below error ..
 __new__() missing 4 required positional arguments: 'time', 'alignments', 'alignment_history', and 'attention_state'

in def seq2seq_model.  Please can you help me ?

**Comment by Olivia-Meng** [comment]
@pranav774 I have the same problem,If you have solved it, please tell me the method.

**Comment by pranav774** [comment]
No I did not... I struggling with it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sofwath** [comment]
change to:
 initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)

also 

inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
                                                                output_time_major=False,
                                                                impute_finished=True,
                                                                maximum_iterations=max_target_length)

and 

training_logits, _ ,_  = tf.contrib.seq2seq.dynamic_decode(training_decoder,
                                                               output_time_major=False,
                                                               impute_finished=True,
                                                               maximum_iterations=max_target_length)

**Comment by ashish9308** [comment]
@pranav774 Resolved or not?

**Comment by asingh9530** [comment]
@pranav774 have you got any solution.

**Comment by chaku88** [comment]
> change to:
> initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)
> 
> also
> 
> inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> 
> and
> 
> training_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)

These changes along with "DynamicAttentionWrapper to AttentionWrapper." works with latest tensorflow version (1.10.1). Thanks @Sofwath

**Comment by asingh9530** [comment]
@Sofwath Thanks it worked

**Comment by HariWu1995** [comment]
@Sofwath Thanks so much. It works for me.

**Comment by SumITUIC** [comment]
> > change to:
> > initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)
> > also
> > inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> > and
> > training_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> 
> These changes along with "DynamicAttentionWrapper to AttentionWrapper." works with latest tensorflow version (1.10.1). Thanks @Sofwath

Can you tell exactly where to make these changes(which file).

**Comment by SumITUIC** [comment]
> > change to:
> > initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)
> > also
> > inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> > and
> > training_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> 
> These changes along with "DynamicAttentionWrapper to AttentionWrapper." works with latest tensorflow version (1.10.1). Thanks @Sofwath

@chaku88 @Abhinavfreecodecamp @Sofwath @HariWu1995  I did these changes to decoding_layer function. But it still gives me error: 
The two structures don't have the same nested structure.

Please help.

**Comment by fendyaugust** [comment]
Can i ask about how to use the model again for testing
When we already trained it in anpther computer?
Please help :(

**Comment by pgup2501** [comment]
@SumITUIC @HariWu1995 
I made the changes as described, however gettign error. 
Tensorflow version : 1.10.0

TypeError: The two structures don't have the same nested structure.

First structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=LSTMStateTuple(c=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state:0' shape=(64, 256) dtype=float32>, h=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state_1:0' shape=(64, 256) dtype=float32>), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float32>)

Second structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_4:0' shape=(?, 256) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_4:0' shape=(?, 256) dtype=float32>)), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float32>)

**Comment by g2sgautam** [comment]
@Abhinavfreecodecamp @chaku88 @HariWu1995  Can you please provide full code

**Comment by dikshakhanna** [comment]
attention_keys, attention_values, attention_score_function, attention_construct_function = tf.contrib.seq2seq.AttentionWrapper(attention_states,attention_option = "bahdanau", num_units=decoder_cell.output_size)

TypeError: __init__() got an unexpected keyword argument 'attention_option

Can anyone solve this issue??

**Comment by kinalmehta** [comment]
replace the complete "decoding_layer" function as : 

```
def decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, inputs_length, targets_length, 
                   max_target_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers, direction):
    '''Create the decoding cell and attention for the training and inference decoding layers'''
    
    with tf.name_scope("RNN_Decoder_Cell"):
        for layer in range(num_layers):
            with tf.variable_scope('decoder_{}'.format(layer)):
                lstm = tf.contrib.rnn.LSTMCell(rnn_size)
                dec_cell = tf.contrib.rnn.DropoutWrapper(lstm, 
                                                         input_keep_prob = keep_prob)
    
    output_layer = Dense(vocab_size,
                         kernel_initializer = tf.truncated_normal_initializer(mean = 0.0, stddev=0.1))
    
    attn_mech = tf.contrib.seq2seq.BahdanauAttention(rnn_size,
                                                  enc_output,
                                                  inputs_length,
                                                  normalize=False,
                                                  name='BahdanauAttention')
    
    with tf.name_scope("Attention_Wrapper"):
        dec_cell = tf.contrib.seq2seq.AttentionWrapper(dec_cell,
                                                              attn_mech,
                                                              rnn_size)
    
    initial_state =  dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)
#     initial_state = tf.contrib.seq2seq.DynamicAttentionWrapperState(enc_state,
#                                                                     _zero_state_tensors(rnn_size, 
#                                                                                         batch_size, 
#                                                                                         tf.float32))

    with tf.variable_scope("decode"):
#         training_logits = training_decoding_layer(dec_embed_input, 
#                                                   targets_length, 
#                                                   dec_cell, 
#                                                   initial_state,
#                                                   output_layer,
#                                                   vocab_size, 
#                                                   max_target_length)
        training_helper = tf.contrib.seq2seq.TrainingHelper(inputs=dec_embed_input,
                                                            sequence_length=targets_length,
                                                            time_major=False)
        training_decoder = tf.contrib.seq2seq.BasicDecoder(dec_cell,
                                                           training_helper,
                                                           initial_state,
                                                           output_layer) 
        training_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
                                            output_time_major=False,
                                            impute_finished=True,
                                            maximum_iterations=max_target_length)
        
    with tf.variable_scope("decode", reuse=True):
#         inference_logits = inference_decoding_layer(embeddings,  
#                                                     vocab_to_int['<GO>'], 
#                                                     vocab_to_int['<EOS>'],
#                                                     dec_cell, 
#                                                     initial_state, 
#                                                     output_layer,
#                                                     max_target_length,
#                                                     batch_size)
        start_tokens = tf.tile(tf.constant([vocab_to_int['<GO>']], dtype=tf.int32), [batch_size], name='start_tokens')
        end_token = (tf.constant(vocab_to_int['<EOS>'], dtype=tf.int32))
        inference_helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(embeddings,
                                                                    start_tokens,
                                                                    end_token)
        inference_decoder = tf.contrib.seq2seq.BasicDecoder(dec_cell,
                                                            inference_helper,
                                                            initial_state,
                                                            output_layer)
        inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
                                            output_time_major=False,
                                            impute_finished=True,
                                            maximum_iterations=max_target_length)

    return training_logits, inference_logits
```

**Comment by ThDarkKnight** [comment]
> > change to:
> > initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)
> > also
> > inference_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> > and
> > training_logits, _ ,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> > output_time_major=False,
> > impute_finished=True,
> > maximum_iterations=max_target_length)
> 
> These changes along with "DynamicAttentionWrapper to AttentionWrapper." works with latest tensorflow version (1.10.1). Thanks @Sofwath

I am running the code on Colab. Can anyone help solving below problem?
After doing those changes, I am getting this error: (version problem?)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-1761e8f20ccb> in <module>()
      5                                                     num_layers,
      6                                                     threshold) 
----> 7             model = build_graph(keep_probability, rnn_size, num_layers, batch_size, learning_rate, embedding_size, direction)
      8             train(model, epochs, log_string)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in __len__(self)
    743     """Returns the rank of this shape, or raises ValueError if unspecified."""
    744     if self._dims is None:
--> 745       raise ValueError("Cannot take the length of shape with unknown rank.")
    746     return len(self._dims)
    747 

ValueError: Cannot take the length of shape with unknown rank.

**Comment by consterwinter** [comment]
> @SumITUIC @HariWu1995
> I made the changes as described, however gettign error.
> Tensorflow version : 1.10.0
> 
> TypeError: The two structures don't have the same nested structure.
> 
> First structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=LSTMStateTuple(c=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state:0' shape=(64, 256) dtype=float32>, h=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state_1:0' shape=(64, 256) dtype=float32>), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float32>)
> 
> Second structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_4:0' shape=(?, 256) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_4:0' shape=(?, 256) dtype=float32>)), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float

**Comment by consterwinter** [comment]
Have you solved this problem?  I get same error too.

**Comment by Kaarthic29** [comment]
Hi,

Any working solution to this problem AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'?
I'm using the TensorFlow version: 1.14.0.
I also tried a few workarounds as mentioned in the above comments but still could not succeed
Any leads or help on this is greatly appreciated.

**Comment by jianhui-ben** [comment]
For AttributeError: **module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'. Check out the answer above:**
change to:
**initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)**
also
**inference_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
output_time_major=False,
impute_finished=True,
maximum_iterations=max_target_length)
and
**training_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(training_decoder,
output_time_major=False,
impute_finished=True,
maximum_iterations=max_target_length)

These changes along with "****DynamicAttentionWrapper to AttentionWrapper**." works with latest tensorflow version (1.14).**


For another error: The two structures don't have the same nested structure.
Go back the initial_state, change it to '**initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state[0])'**, instead of 
'initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)'

**Comment by sannge** [comment]
> @SumITUIC @HariWu1995
> I made the changes as described, however gettign error.
> Tensorflow version : 1.10.0
> 
> TypeError: The two structures don't have the same nested structure.
> 
> First structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=LSTMStateTuple(c=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state:0' shape=(64, 256) dtype=float32>, h=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state_1:0' shape=(64, 256) dtype=float32>), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float32>)
> 
> Second structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_4:0' shape=(?, 256) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_4:0' shape=(?, 256) dtype=float32>)), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float



> @SumITUIC @HariWu1995
> I made the changes as described, however gettign error.
> Tensorflow version : 1.10.0
> 
> TypeError: The two structures don't have the same nested structure.
> 
> First structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=LSTMStateTuple(c=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state:0' shape=(64, 256) dtype=float32>, h=<tf.Tensor 'AttentionWrapperZeroState/checked_cell_state_1:0' shape=(64, 256) dtype=float32>), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float32>)
> 
> Second structure: type=AttentionWrapperState str=AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/fw/fw/while/Exit_4:0' shape=(?, 256) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_3:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'encoder_1/bidirectional_rnn/bw/bw/while/Exit_4:0' shape=(?, 256) dtype=float32>)), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(64, 256) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=(64, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'AttentionWrapperZeroState/zeros_3:0' shape=(64, ?) dtype=float

did you solve the problem by any chance? I got the same issue here.

**Comment by splendidbug** [comment]
> For AttributeError: **module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'. Check out the answer above:**
> change to:
> **initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)**
> also
> **inference_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> and
> **training_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> 
> These changes along with "****DynamicAttentionWrapper to AttentionWrapper**." works with latest tensorflow version (1.14).**
> 
> For another error: The two structures don't have the same nested structure.
> Go back the initial_state, change it to '**initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state[0])'**, instead of
> 'initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)'

This worked well, thanks. 
PS: It gave an error related to max_target_length, so just replace it with max_summary_length

**Comment by ayoubzeis** [comment]
> For AttributeError: **module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'. Check out the answer above:**
> change to:
> **initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)**
> also
> **inference_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> and
> **training_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> 
> These changes along with "****DynamicAttentionWrapper to AttentionWrapper**." works with latest tensorflow version (1.14).**
> 
> For another error: The two structures don't have the same nested structure.
> Go back the initial_state, change it to '**initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state[0])'**, instead of
> 'initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)'

thanks it,s works for me you save me thanks a lot

**Comment by spandanag333** [comment]
> For AttributeError: **module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'. Check out the answer above:**
> change to:
> **initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)**
> also
> **inference_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> and
> **training_logits, _ ,_** = tf.contrib.seq2seq.dynamic_decode(training_decoder,
> output_time_major=False,
> impute_finished=True,
> maximum_iterations=max_target_length)
> 
> These changes along with "****DynamicAttentionWrapper to AttentionWrapper**." works with latest tensorflow version (1.14).**
> 
> For another error: The two structures don't have the same nested structure.
> Go back the initial_state, change it to '**initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state[0])'**, instead of
> 'initial_state = dec_cell.zero_state(batch_size=batch_size,dtype=tf.float32).clone(cell_state=enc_state)'



I have tried that and I am getting the below error. Please help me out. I am using tensorflow 1.14.0
TypeError: decoding_layer() missing 1 required positional argument: 'direction'
